language: php
php:
  - "5.4"

before_script:
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script:
  - phpunit -v -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
