CREATE TABLE `anunturi_angajare` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `companieID` int(11) DEFAULT NULL,
  `denumire` varchar(255) DEFAULT NULL,
  `pozitii` int(3) DEFAULT '1',
  `program_lucru` enum('part-time','full-time') DEFAULT NULL,
  `durata_contract` enum('nedeterminata','determinata') DEFAULT NULL,
  `descriere` varchar(5000) DEFAULT NULL,
  `profil_scoala_primara` int(1) DEFAULT '0',
  `profil_scoala_profesionala` int(1) DEFAULT '0',
  `profil_liceu` int(1) DEFAULT '0',
  `profil_facultate` int(1) DEFAULT '0',
  `profil_postuniversitar` int(1) DEFAULT '0' COMMENT 'no-comment',
  `cerinte` varchar(5000) DEFAULT NULL,
  `avangaje_oferite` varchar(5000) DEFAULT NULL,
  `persoanacontact_nume` varchar(255) DEFAULT '-Fullname-',
  `persoanacontact_telefon` varchar(30) DEFAULT '555-000-222',
  `persoanacontact_adresa_localitate` varchar(255) DEFAULT NULL,
  `persoanacontact_adresa_strada` varchar(255) DEFAULT NULL,
  `persoanacontact_adresa_nr` varchar(20) DEFAULT NULL,
  `data_angajare` date DEFAULT NULL,
  `data_expirare` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT 'This column has 0 as default',
  PRIMARY KEY (`id`),
  KEY `companieID` (`companieID`),
  KEY `ProfilEducatie` (`profil_scoala_primara`,`profil_scoala_profesionala`,`profil_liceu`,`profil_facultate`,`profil_postuniversitar`),
  KEY `pozitii` (`pozitii`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=latin1;
